name: s-System
version: '${project.version}'
main: de.Barryonixx.Main
api-version: 1.17

commands:
  wetter:
    aliases:
      - weather
  gm:
    aliases:
      - gamemode
  pay:
  money:
  clearchat:
    aliases:
      - cc
      - cchat
      - chatclear
  message:
    aliases:
      - msg
